### ISSUE TITLE
need help about an example

### ISSUE THREAD

**Issue by nuitlejour** [NOAA-GFDL/GFDL-VortexTracker#6]
Dear tim, 
I have tried to run tc tracker in tcgen mode with data converted from wrf, I have create an empty fort.14 and lead time in fort.15, 

the namelist.gettrk is:

[namelist.gettrk.txt](https://github.com/NOAA-GFDL/GFDL-VortexTracker/files/11563250/namelist.gettrk.txt)

the output from gettrk_main is as follows:
[output.txt](https://github.com/NOAA-GFDL/GFDL-VortexTracker/files/11563236/output.txt)

example data converted from wrf:
https://www.dropbox.com/scl/fo/7c2gql0e77woovv74736b/h?dl=0&rlkey=fmpnysxcxv8i0wlun3at8uo0q

After many tries, I could not get tc tracker to find any hurricane (I am sure there is one in the example data), and finally there was an error, saying: "Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG"

could you please have a look at the example data for me? I have been at it for about a month now, and going nowhere.

Also, could you please add an official test data to this repo, so that users can test its functionality? And could you please update the user's manual? the dt-center version is quite old, and may differ from the new version

Thank you for your time!

**Comment by mcallic2** [comment]
Hey @nuitlejour,

I know this issue was created over a year ago, but I was wondering if this was ever resolved?
I am managing this repo now & there has been quite a few updates/upgrades that I think will answer some of your questions in this issue.
Let me know how I can help or if I can close this issue

**Comment by shiliutree** [comment]
Could anyone provide a copy of the  "test_data.tar.gz"? The DTC no longer proved this file.

**Comment by mcallic2** [comment]
@shiliutree I am not sure what that file is

**Comment by nuitlejour** [comment]
@mcallic2 , I have just read the message, the issue has not been solved, can you please provide an official test suite in netcdf format, so that I can pin point the problem on my end?
Thank you for your time.

**Comment by mcallic2** [comment]
@nuitlejour A testing suite is in the process of being created, but will not be finished for some time.
However, there has been some significant changes to this repo so I would suggest cloning fresh and following the instructions in the README, after you try running with your data using the new provided runscript I could offer more help if it's needed.

**Comment by shiliutree** [comment]
I am using "standalone_gfdl-vortextracker_v3.9a.tar.gz" which was supported
by DTC on the link "Community Code | Legacy Tools | dtcenter.org
<https://dtcenter.org/community-code-legacy-tools>". After a recent overhaul
of the DTC website, I cannot find the download link for "test_data.tar.gz"
which should be along with the standalone software. Could you share me the
download link or a copy of this file? Thank you very much.

**Comment by mcallic2** [comment]
@shiliutree Ahh, I see the problem. We, as in Tim and I, do not manage or maintain any of the code from that website. I understand the confusion though. That community used very outdated source code from this tracker's repository but we do not have access or knowledge of other code/files that were created from the DTC community

**Comment by Saiful1234rr** [comment]
Can anyone tell me how can I manage test_data.tar.gz this data. Or anyone can provide me this data.
